<div class="imagenfondo">
<h3 class="about" >ABOUT US</h3>
<p class="aboutP" >DANZEFLOOR IS A SITE FOR YOU TO BE ABLE TO SHARE YOUR OWN MUSIC CHOOSING DIFFERENT AUDIO FORMATS AND MONETISE IT. ALSO FANS WILL GET NOTICE ABOUT YOUR COMING UP EVENTS. USERS COULD DOWNLOAD YOUR MUSIC TO MIX TOO</p>
</div>
